import { LegalPage, Bullet } from "@/components/aeo/legal-page";

export const metadata = {
  title: "Terms of Service — Free AEO",
  description:
    "Terms governing the use of Free AEO (aeotool.top), including the AI visibility checker, reports, and related services.",
};

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Terms of Service"
      title="Terms of Service"
      description="Last updated: June 2026. These Terms of Service govern your use of Free AEO (aeotool.top) and its related tools and services."
    >
      <h2>1. Acceptance of terms</h2>
      <p>
        By accessing or using Free AEO (aeotool.top) (the "Service"), you agree to be bound by
        these Terms of Service. If you do not agree with these terms, please discontinue use of
        the Service.
      </p>

      <h2>2. Description of service</h2>
      <p>
        Free AEO provides an Answer Engine Optimization (AEO) visibility checker designed to help
        users analyze brand visibility across AI answer platforms. The Service may generate AI
        visibility reports, sentiment analysis, mention tracking, and related insights.
      </p>

      <p>
        In addition to the free analyzer, Free AEO may offer paid audits, consulting, AI
        optimization services, and other related products.
      </p>

      <h2>3. Use of the service</h2>
      <p>
        You agree to use the Service only for lawful purposes and in a manner that does not:
      </p>

      <ul>
        <Bullet>Violate applicable laws or regulations</Bullet>
        <Bullet>Infringe upon the rights of third parties</Bullet>
        <Bullet>Attempt to reverse-engineer, disrupt, or overload the Service</Bullet>
        <Bullet>Use automated abuse, spam, or malicious requests</Bullet>
        <Bullet>Use the Service for deceptive, harmful, or illegal activities</Bullet>
      </ul>

      <h2>4. Accuracy of results</h2>
      <p>
        AI visibility reports and scores generated by Free AEO are intended for informational and
        analytical purposes only. Results are based on available AI models, algorithms, and
        estimation methods and should not be interpreted as guarantees of rankings, citations,
        mentions, or future performance.
      </p>

      <p>
        Because AI systems evolve continuously, actual responses from platforms such as ChatGPT,
        Gemini, Perplexity, or other answer engines may vary over time. Users should exercise
        independent judgment when making business decisions.
      </p>

      <h2>5. Intellectual property</h2>
      <p>
        The Free AEO brand, website design, software, graphics, documentation, and original
        content are protected by applicable intellectual property laws.
      </p>

      <p>
        You may not reproduce, redistribute, copy, or republish our materials without prior
        permission. Analysis reports generated from your own submitted information remain yours to
        use.
      </p>

      <h2>6. Paid services</h2>
      <p>
        Paid audits, consulting, and optimization services may be offered separately from the free
        analyzer. Pricing, scope, timelines, and deliverables for such services are communicated
        before payment is requested.
      </p>

      <p>
        Unless otherwise stated, fees paid for completed services are non-refundable.
      </p>

      <h2>7. Limitation of liability</h2>
      <p>
        The Service is provided on an "as is" and "as available" basis without warranties of any
        kind. To the maximum extent permitted by applicable law, Free AEO shall not be liable for
        any indirect, incidental, consequential, or business-related damages resulting from the
        use of the Service or reliance on generated reports.
      </p>

      <h2>8. Third-party links</h2>
      <p>
        The website may contain links to external websites, tools, APIs, or partner resources.
        Free AEO is not responsible for the availability, content, privacy practices, or policies
        of third-party services.
      </p>

      <h2>9. Changes to the service and terms</h2>
      <p>
        We reserve the right to modify, improve, suspend, or discontinue any part of the Service
        at any time without prior notice.
      </p>

      <p>
        These Terms of Service may also be updated periodically. Continued use of the Service
        following any updates constitutes acceptance of the revised terms.
      </p>

      <h2>10. Governing law</h2>
      <p>
        These Terms of Service shall be governed by and interpreted in accordance with applicable
        laws in the jurisdiction in which the Service operates, without regard to conflict-of-law
        principles.
      </p>

      <h2>11. Contact</h2>
      <p>
        If you have questions regarding these Terms of Service, please visit our{" "}
        <a
          href="/contact"
          className="font-semibold text-primary hover:underline"
        >
          contact page
        </a>{" "}
        or email{" "}
        <a
          href="mailto:hello@idilsh.top"
          className="font-semibold text-primary hover:underline"
        >
          hello@idilsh.top
        </a>
        .
      </p>
    </LegalPage>
  );
}


